services:
  - type: web
    name: effoi-restaurant
    runtime: python
    repo: https://github.com/Tesfay-Tesfu/effoibarandrestaurant
    plan: free
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn "backend.effoi_app:app" --workers=2 --threads=4 --timeout=120 --bind=0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: effoi-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: BASE_URL
        value: https://www.effoirestaurant.com
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: effoi-db
    plan: free
    databaseName: effoi
    user: effoi_user
